### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by VasilisKos** [kofuk/SecureScreen#1]
1. A dark theme would be great. Please add it. 
2. Add a tile shortcut, that will activate the notification and pin the app instantly.

**Comment by kofuk** [comment]
Hi. Thank you for requesting these features.

Though I'd like to add these features, I'm no longer working on Android apps, and I'm too busy to catch up to the latest Android development.
I'll try to implement these features in my free time, but it should take long time.
If you can't wait until I work on these (or you want to working on these features), PR is welcomed.

Thank you.

**Comment by kofuk** [comment]
Also, I have a question.

What do you exactly mean by "tile shortcut"? App widgets, or a floating icon, or another?

**Comment by VasilisKos** [comment]
A tile shortcut. In the notifications drawer. Like the ones for WiFi, data etc

**Comment by kofuk** [comment]
I now understood what you mention.
Thank you.

**Comment by kofuk** [comment]
Dark theme in included in the released version!
Quick Settings tile is in development and will be released soon!
